apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: mesh-workload
  namespace: mesh-workload
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.1
  gateways:
    enabled: true
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 2
    egress:
      enabled: false
    openshiftRoute:
      enabled: false