---
# Source: jump-app/charts/jump-app-micros/templates/istio/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: traffic
  namespace: mesh-egress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
      - '*'
      tls:
        mode: MUTUAL
        serverCertificate: /etc/istio/mtls-certs/egress.crt
        privateKey: /etc/istio/mtls-certs/egress.key
        caCertificates: /etc/istio/mtls-certs/ca-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic
  namespace: mesh-egress
spec:
  gateways:
  - traffic
  hosts:
  - www.google.com
  http:
  - route:
      - destination:
          host: www.google.com
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
  namespace: mesh-egress
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
